# Generated by Django 3.2.5 on 2021-08-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_mode', '0001_initial'),
        ('purchase', '0029_alter_purchase_purchasedate'),
        ('partner', '0008_partner_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paymentNumber', models.CharField(max_length=512)),
                ('paymentDate', models.DateField()),
                ('notes', models.TextField(null=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_mode.paymentmode')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner.partner')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.purchase')),
            ],
        ),
    ]
