# Generated by Django 3.2.5 on 2021-07-27 14:07

from django.db import migrations, models
import django.db.models.deletion
import enum


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_opportunity', '0020_alter_purchaseopportunity_status'),
        ('purchase', '0021_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase_opportunity.purchaseopportunity'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('COMPLETED', 'COMPLETED')], default=enum.Enum.__str__, max_length=128),
        ),
    ]
