# Generated by Django 3.2.5 on 2021-08-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0027_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('COMPLETED', 'COMPLETED')], default='STARTED', max_length=128),
        ),
    ]
