# Generated by Django 3.2.5 on 2021-08-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0029_alter_purchase_purchasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
