# Generated by Django 3.2.5 on 2021-07-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('alpha3Code', models.CharField(max_length=50, null=True)),
                ('alpha2Code', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainAddress', models.CharField(max_length=256)),
                ('additionalAddress', models.CharField(max_length=256, null=True)),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.country')),
            ],
        ),
    ]
