# Generated by Django 3.2.5 on 2021-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
