# Generated by Django 3.2.5 on 2021-07-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('birthDate', models.DateField()),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('firstContactDate', models.DateTimeField()),
                ('comments', models.CharField(max_length=2048)),
            ],
        ),
    ]
