# Generated by Django 3.2.5 on 2021-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='comments',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='firstContactDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='mobile',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
