# Generated by Django 3.2.5 on 2021-07-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20210712_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
