# Generated by Django 3.2.5 on 2021-07-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner_type', '0001_initial'),
        ('partner', '0003_partner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partnerType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='partner_type.partnertype'),
            preserve_default=False,
        ),
    ]
