# Generated by Django 3.2.5 on 2021-07-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('partner', '0006_partner_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.address'),
        ),
    ]
