# Generated by Django 3.2.5 on 2021-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_alter_partner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='gender',
            field=models.CharField(choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MS', 'MS'), ('UNDEFINED', 'UNDEFINED')], default='UNDEFINED', max_length=128),
        ),
    ]
