# Generated by Django 3.2.5 on 2021-07-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0004_partner_partnertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('expectedEndingDate', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('INTERESTED', 'INTERESTED'), ('ON_GOING', 'ON_GOING'), ('CONVERTED', 'CONVERTED'), ('NOT_CONVERTED', 'NOT_CONVERTED')], max_length=128)),
                ('comments', models.TextField(max_length=2048)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner.partner')),
            ],
        ),
    ]
