# Generated by Django 3.2.5 on 2021-07-18 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('purchase_opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseopportunity',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseopportunity',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
