# Generated by Django 3.2.5 on 2021-07-19 19:16

import django.core.validators
from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_opportunity', '0004_alter_purchaseopportunity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseopportunity',
            name='priority',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='purchaseopportunity',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('INTERESTED', 'INTERESTED'), ('ON_GOING', 'ON_GOING'), ('CONVERTED', 'CONVERTED'), ('NOT_CONVERTED', 'NOT_CONVERTED')], default=enum.Enum.__str__, max_length=128),
        ),
    ]
