# Generated by Django 3.2.5 on 2021-08-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('purchase_opportunity', '0024_alter_purchaseopportunity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseopportunity',
            name='products',
            field=models.ManyToManyField(related_name='products', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='purchaseopportunity',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('INTERESTED', 'INTERESTED'), ('ON_GOING', 'ON_GOING'), ('CONVERTED', 'CONVERTED'), ('NOT_CONVERTED', 'NOT_CONVERTED')], default='NEW', max_length=128),
        ),
    ]
